### ISSUE TITLE
User Story #13

### ISSUE THREAD

**Issue by Fishernab** [seigle15/Double-Sean-with-a-side-of-Data#13]
As a programmer, I want to create a database to store our program data, a container class that manages the content of said database, and initializes the necessary container objects within the program so that the developers of this project can easily access and manipulate the necessary data being represented in our UI.

**Comment by AustinStewart95** [comment]
As a programmer, I want to create a database to store our program data, a container class that manages the content of said database, and initializes the necessary container objects within the program so that the developers of this project can easily access and manipulate the necessary data being represented in our UI
1.	Assumptions:
a.	Have a list of restaurants and all corresponding data saved within a text file.
b.	Have a separate text file for any additional restaurants to be added.
2.	Tasks:
a.	Create a data base that is easy to navigate.
3.	Tests:
a.	The programmer is able to access all available information of all restaurants with ease.
4.	Definition of Done: The programmer can access all information of any restaurants with ease.
